### ISSUE TITLE
Dúvidas

### ISSUE THREAD

**Issue by PauloBoaventura** [tchaguitos/correios-rest#5]
Este código esta funcionando em PHP 5, 5.6, 7.0, 7.1 ou até mesmo em 7.2 ?
São muitas dúvidas e nada pessoal... (Já deixo claro)
Este código esta nas normativas novas dos correios (2017) e que pelo visto já existe novas normativas em (2018)...
Bom, este não é o único que visualizamos que aparentemente esta tudo correto.
Mas, tenho que ser este USUÁRIO questionador, já que estamos enfrentando tantos problemas seja eles em PHP, AJAX ou qualquer impulso anterior á 2017.
E assim vem as dúvidas...

Gostaria de saber se podemos implementar este código em outras ferramentas e até mesmo em outas plataformas... 

Espero que tenhamos uma resposta satisfatória e um UPGRADE. (O que neste notamos que o upgrade é notavel).

S.O = Centos7 - Plesk
Php = 5.6 / 7.0

**Comment by tchaguitos** [comment]
Opa, tudo bem, @PauloBoaventura?

Não entendi bem a sua dúvida mas, de qualquer maneira, todo esse código integra uma API que apenas lê e altera o formato da resposta do webservice dos correios, mantendo os resultados.

O código está escrito em javascript e será feito o deploy para um servidor e os devs poderão enviar uma requisição com as informações requeridas e especificadas na documentação para cada endpoint e a API responderá com a resposta vinda do webservice dos correios convertida pra JSON.

**Comment by PauloBoaventura** [comment]
Olá @tchaguitos 
Bom minha dúvida era se esta implementação estava funcionando.
E o meu problema é colocar um código na plataforma magento 1.9 ou 2.1, que funcione para calculo de frete e que insira o valor deste, no final do pedido.

Se souber algo... Por favor compartilhe!
Abs!

**Comment by tchaguitos** [comment]
Tudo bem, @PauloBoaventura!

Você precisaria só calcular o valor do frete baseado na data atual? Posso subir uma máquina na Heroku com essa API e você consultar através do front-end da sua loja.

**Comment by PauloBoaventura** [comment]
Opa, @tchaguitos 
Sim preciso calcular e inserir o valor deste no final do pedido...
Sim costumo usar através de front-end...

Sua ajuda será muito util!!!
